name: Build Polaris Javadoc

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew javadoc

      - uses: actions/upload-artifact@v2
        with:
          name: polaris-javadoc
          path: polaris-application/build/docs/javadoc/

      - uses: jakejarvis/s3-sync-action@master
        if: github.ref == 'refs/heads/main'
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'polaris-controller.ractf.co.uk'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'
          SOURCE_DIR: 'polaris-application/build/docs/javadoc'

      - uses: actions/upload-artifact@v2
        with:
          name: polaris-javadoc
          path: polaris-api/build/docs/javadoc/

      - uses: jakejarvis/s3-sync-action@master
        if: github.ref == 'refs/heads/main'
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'polaris-api.ractf.co.uk'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'
          SOURCE_DIR: 'polaris-api/build/docs/javadoc'

      - uses: actions/upload-artifact@v2
        with:
          name: polaris-javadoc
          path: polaris-apiclient/build/docs/javadoc/

      - uses: jakejarvis/s3-sync-action@master
        if: github.ref == 'refs/heads/main'
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'polaris-apiclient.ractf.co.uk'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'
          SOURCE_DIR: 'polaris-apiclient/build/docs/javadoc'
