name: Dependency Submission
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@v0.8.4
        with:
          sub-module-mode: INDIVIDUAL_DEEP
          gradle-build-module: |-
            :
            :polaris-api
            :polaris-apiclient
            :polaris-application
            :polaris-cli
            :polaris-integration-tests
            :polaris-testlib
        
